name: GitHub Issue Notification

on:
  issues:
    types: [labeled]

jobs:
  notify_mattermost:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Send notification to MatterMost
        id : send-to-mattermost
        if: github.event.label.name == 'ğŸ™‹â€â™‚ï¸ suggestion'
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        run: |
          ISSUE_TITLE=$(curl -sS "${{ github.event.issue.url }}" | jq -r '.title')
          MESSAGE="ğŸ™‹â€â™‚ï¸ ìƒˆë¡œìš´ ì´ìŠˆê°€ ì—´ë ¸ì–´ìš¥!!: $ISSUE_TITLE\n${{ github.event.issue.html_url }}"
          curl -X POST -H "Content-type: application/json" --data "{\"text\":\"$MESSAGE\"}" $MATTERMOST_WEBHOOK_URL
